apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "realworld.frontendFullName" . }}
  labels:
    {{- include "realworld.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "realworld.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "realworld.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 4100
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/tags/
              port: http
          readinessProbe:
            httpGet:
              path: /api/tags/
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: MONGODB_URI
              value: mongodb://root:hello@{{ .Release.Name }}-mongodb
            - name: NODE_ENV
              value: production
            - name: SECRET
              value: shhhhhh
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
