apiVersion: v1
kind: Service
metadata:
  name: {{ include "realworld.frontendFullName" . }}
  labels:
    {{- include "realworld.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "realworld.selectorLabels" . | nindent 4 }}
